### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by suhlig** [tonobo/hcloud-ruby#14]
Thanks for maintaining this gem. It's already helpful - I use it to manage my son's Minecraft server (which is, as you can imagine, pretty essential for a 14-year old).

Keep up the good work!

**Comment by tonobo** [comment]
I recently released a new version, try it out and have fun :D

It's less redundant so easier to be feature complaint with the upstream api.

**Comment by mm580486** [comment]
excelent, please keep up @tonobo
