### ISSUE TITLE
Documentation for busy waiting

### ISSUE THREAD

**Issue by elconas** [tonobo/hcloud-ruby#2]
Thanks for the gem,
how can I "busy wait" for an Action to complete. This does not update the status of the action:

```
action,server = c.servers.create(name: "moo5", server_type: "cx11", image: "ubuntu-16.04")

while true do
  puts action.status
  puts server.status
  puts server.public_net["ipv4"]
  sleep 1
end
```

In general how to I refetch a server or any other resource for status updates ?

**Comment by tonobo** [comment]
Thanks for using it. I'm not sure how to resolve this problem. Normally you just need to wait for action state != running. 

The library is currently also missing pagination support and floating ip handling. I've a managed client on  my todo, too. This shouldn't be just a low level api client. The managed client should auto-poll for action finish, in a modarate poll level to not reach the rate limits.

Possibly this will help you:

```ruby
while action.status == "running"
  sleep 1
end
```

**Comment by elconas** [comment]
Actually the "find" action was the missing link.

This works:

```
action,server = c.servers.create(name: "moo5", server_type: "cx11", image: "ubuntu-16.04")

while action.status == "running"
  puts "Waiting for Action #{action.id} to complete ..."
  action = c.actions.find(action.id)
  server = c.servers.find(server.id)
  puts "Action Status: #{action.status}"
  puts "Server Status: #{server.status}"
  puts "Server IP Config: #{server.public_net["ipv4"]}"
  sleep 5
end
```

I think it is worth adding it do the documentation.

**Comment by tonobo** [comment]
Oh, great. I'll close the issue if the readme has been updated :smile: .
