### ISSUE TITLE
question: could you point out the differences to other hcloud gem?

### ISSUE THREAD

**Issue by whysthatso** [tonobo/hcloud-ruby#71]
it might make sense to delineate it from:
https://github.com/floriandejonckheere/hcloud

**Comment by tonobo** [comment]
well this project started about 5 years ago, maybe ask the maintainer from the other project why he started a new project. I don't know the reason for it.

**Comment by whysthatso** [comment]
ups, yeah, i missed that age difference...
will ask over there.
